// <auto-generated />
using ExploreCalifornia.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;

namespace ExploreCalifornia.Migrations
{
    [DbContext(typeof(ExploreCaliforniaContext))]
    partial class ExploreCaliforniaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExploreCalifornia.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("IncludesMeals");

                    b.Property<int>("Length");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.Property<string>("Rating");

                    b.HasKey("Id");

                    b.ToTable("Tour");
                });

            modelBuilder.Entity("ExploreCalifornia.Models.Booking", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("TourID");

                b.Property<bool>("TourName");

                b.Property<int>("ClientID");

                b.Property<DateTime>("DepartureDate");

                b.Property<int>("NumberOfPeople");

                b.Property<string>("FullName");
                b.Property<string>("Email");
                b.Property<string>("ContactNo");
                b.Property<string>("SpecialRequest");

                b.HasKey("Id");

                b.ToTable("Booking");
            });
#pragma warning restore 612, 618
        }
    }
}
